### ISSUE TITLE
SpookyHashV2 hashes do not match official implementation

### ISSUE THREAD

**Issue by mulgarz** [brandondahler/Data.HashFunction#30] opened 2017-10-27 20:04 UTC
The 32 bit spookyhashv2 of the string "hello world" should be UInt32 "2617184861" according to the official implementation But with this library it is not.

I have tested all possible ways of feeding this string including different encodings and none of them match.

Testing the same thing with other libraries and this website match properly
https://asecuritysite.com/encryption/Spooky

**Comment by brandondahler** [comment] 2017-11-02 02:01
Going through the history, it appears that the initial implementation was never correct and therefore all versions of Data.HashFunction.SpookyHash have been producing incorrect values, checked against incorrect test vectors.  Because of this, I am going to unlist all existing versions of this package from NuGet.

I will fix and re-release a fixed implementation as soon as I am able to.

**Comment by brandondahler** [comment] 2017-11-25 06:52
Looking at the implementation, it appears that the root cause of the error is because it was incorrectly assumed that the Short(...) function call for byte lengths of 192 and less were just optimizations of the core hash implementation.  

This assumption is incorrect -- SpookyHash has a slightly different hash generation implementation for input values of <= 192 bytes in length.

The net effect is that we have been producing incorrect results for all values <= 192 bytes in length.

**Comment by brandondahler** [comment] 2018-03-27 03:49
I have verified that this has been resolved in v2.0.

**Closed** 2018-03-27 04:06 UTC
Labels: bug, confirmed
