### ISSUE TITLE
Potential .NET Core Migration

### ISSUE THREAD

**Issue by antoinne85** [brandondahler/Data.HashFunction#29] opened 2017-09-21 01:17 UTC
My company is currently considering porting some of our projects over to .NET Core and your MurmurHash library (and its dependencies) are in use all over the place (requiring us to either swap out the hashing algorithm in use or to migrate your libraries to move forward).

Do you have any plans to prepare these libraries for use with .NET Core/Standard? If not, would you be open to a PR that does so?

**Comment by antoinne85** [comment] 2017-09-21 01:23
I'll add that according to https://docs.microsoft.com/en-us/dotnet/standard/net-standard, it looks like a migration would still be able to support folks on .NET Framework 4.5 (the current target framework, if I've not missed anything in examining the repository). That'd put this project on .NET Standard 1.0.

**Comment by brandondahler** [comment] 2017-09-25 02:05
See #24 .  I have been working on v2.0 for a little while now -- that will implement the minimal netstandard versions based on the requirements of each hash function (netstandard1.1 for most, 1.3 for HashAlgorithmWrapper for instance).  There is a pre-release build of 2.0.0 based on the DotNetCore branch, but there are a number of API changes that version does not have quite yet.

I'd welcome any pull requests, but if you plan on updating any .NET core related things, you'll want to branch off of the DotNetCore branch.

**Comment by brandondahler** [comment] 2017-11-25 03:11
Closing as duplicate of #24

**Closed by brandondahler** 2017-11-25 03:11 UTC
Labels: duplicate
